version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sqlalchemy
    versions:
    - 1.3.22
    - 1.3.23
    - 1.4.0
    - 1.4.1
    - 1.4.2
    - 1.4.3
    - 1.4.4
    - 1.4.5
    - 1.4.6
    - 1.4.7
    - 1.4.8
    - 1.4.9
  - dependency-name: twilio
    versions:
    - 6.51.1
    - 6.52.0
    - 6.53.0
    - 6.54.0
    - 6.55.0
    - 6.56.0
  - dependency-name: phonenumbers
    versions:
    - 8.12.17
    - 8.12.18
    - 8.12.19
    - 8.12.20
  - dependency-name: pyflakes
    versions:
    - 2.3.0
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: alembic
    versions:
    - 1.5.6
    - 1.5.7
  - dependency-name: pyjwt
    versions:
    - 2.0.1
  - dependency-name: flask-migrate
    versions:
    - 2.6.0
    - 2.7.0
  - dependency-name: flask
    versions:
    - "1.0"
  - dependency-name: xmlunittest
    versions:
    - 0.5.0
  - dependency-name: flask-script
    versions:
    - 2.0.6
  - dependency-name: coverage
    versions:
    - "5.4"
  - dependency-name: lxml
    versions:
    - 4.6.2
  - dependency-name: flask-sqlalchemy
    versions:
    - 2.4.4
