language: python
python:
  - '2.7'
  - '3.4'
install:
  - pip install -r requirements.txt
  - pip install coveralls
env:
  global:
  - DEBUG=False
  - SECRET=SuperSecret
  - SQLALCHEMY_DATABASE_URI=sqlite://survey.sqlite
script:
  - coverage run --source=automated_survey_flask manage.py test
after_script:
  - coverage report
